### ISSUE TITLE
error in pull request for milestone -0

### ISSUE THREAD

**Issue by khawla-banydomi** [JJ/CC-20-21#122] opened 2020-10-18 09:59 UTC
@JJ my professor I have an error in the pull request and it is due to multi files change and missing ] prometo in the template; how can I fix it..thanks in advance

#118

**Comment by JJ** [comment] 2020-10-18 10:16
I already answered in #121, which I closed.

> The errors in the submission are there so that the student can learn what's wrong and fix it. By fixing them, you prove you have learned the concepts that are going to be graded later.

The problem is that you keep trying to replay your former actions, without understanding what you need to do and why. From the PR, you need to learn, and learn well
* Markdown
* How to update a repository from an upstream repository, in this case the class repository, and why you need to do it.
* What is the difference between a `pull` and a `pull --rebase` (which, BTW you have marked as done but it shows clearly you have not).
* What is a pull request and what it means. I gave you [here](https://github.com/JJ/CC-20-21/pull/113#issuecomment-710788778) some resources to do that, yet you kept doing the same in the next PR.

Prior to making this submission, [you need to understand how Git and GitHub work correctly](http://jj.github.io/CC/documentos/proyecto/0.Repositorio). That's an objective of the first week, and [you have marked that objective as achieved](https://github.com/JJ/CC-20-21/blob/master/objetivos/khawla-banydomi.md). Well, you need to prove, by making correctly a PR to submit your first milestone, that you have actually done so.
I am closing this issue now. Please don't open another one. Just read carefully, learn the basic topics you need to learn, don't check-mark as "done" what you haven't done, and once you learn all the topics above, please re-do your PR (without closing it).

**Closed by JJ** 2020-10-18 10:16 UTC
